### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by bankairyuu** [robotjatek/Brainfuck.NET#1]
Szia Atti! :D
Készíts egy README.md-t, hogy mi készül, kíváncsi vagyok mit tevékenykedsz 👍

**Comment by robotjatek** [comment]
Üdv :D
Csak egy közel 2 évvel ezelőtti, céges unatkozós délutánon készült szösszenetet mentettem meg a régi gépemről.
Röviden: Brainfuck kódot fordít le a DotNet köztes nyelvére a CIL-re (leánykori nevén MSIL). Aztán kiköp egy .exe-t amit már a dotnet futtat.
De majd valamelyik nap összerakok hozzá egy readme-t :D

**Comment by robotjatek** [comment]
Csak 5 év telt el és teljesült is a kívánságod!
